name: Filebeat-Alpine
description: Log Shipper to logstash

version: 6.1.1
category: Shipper
maintainer: "Eason Lau <eason.lau02@hotmail.com>"
license: MIT
projectURL: https://github.com/easonlau02/filebeat-alpine
